name = "groundwire"
main = "src/index.js"
compatibility_date = "2023-11-21"
account_id = "8d54d3d908d8e050fb781d3c36265501"

[vars]
# Currency that will be shown in Groundwire (see the screenshot)
CURRENCY = 'CAD'
# VOIP username
VOIP_USERNAME = 'XXXXXX@XXXX.com'
# !! Define VOIP_PASSWORD via `wrangler secret put VOIP_PASSWORD`

[placement]
mode = "smart"
