name = "groundwire"
main = "src/index.js"
compatibility_date = "2024-11-21"

[vars]
# Currency that will be shown in Groundwire (see the screenshot)
CURRENCY = 'CAD'
# VOIP username - replace with your actual VOIP.MS email
VOIP_USERNAME = 'XXXX@XXXX.XXX'
# Replace with your API (!) password
# Note that it's not your voip.ms password. See the Readme for activation steps
VOIP_PASSWORD = 'XXXX'
# Required auth token between Cloudflare and Groundwire app
TOKEN = 'XXXXX'

[observability.logs]
enabled = true

[placement]
mode = "smart"
